apiVersion: apps/v1
kind: Deployment
metadata:
  name: xobseu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xobseu
  template:
    metadata:
      labels:
        app:xobseu
    spec:
      containers:
      - image: okteto.dev/xobseu:latest
        name:xobseu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "905cfc06-2da3-4fb6-9878-6ad785170724"
        - name: Vless_Path
          value: "/905cfc06-2da3-4fb6-9878-6ad785170724"
        - name: Vmess_UUID
          value: "c862055b-a761-494d-a845-4385ce4151ee"
        - name: Vmess_Path
          value: "/c862055b-a761-494d-a845-4385ce4151ee"
        - name: Share_Path
          value: "/v2link"
